### ISSUE TITLE
More conferences?

### ISSUE THREAD

**Issue by xuhangc** [DmitryRyumin/NewEraAI-Papers#3]
Hi, I am wondering if you consider including more conferences on multimedia or graphics?

**Comment by DmitryRyumin** [comment]
Hi @xuhangc,

Next year, I plan to add support for ACM Multimedia and SIGGRAPH. For this year, I plan to fill all the conferences listed in this repository and support them every year.

**Comment by xuhangc** [comment]
> Hi @xuhangc,
> 
> Next year, I plan to add support for ACM Multimedia and SIGGRAPH. For this year, I plan to fill all the conferences listed in this repository and support them every year.

Thx. That would be very helpful! 😃
